Repository LINKLE-2025/LINKLE_Frontend, pull requests merged in 2025-09, with the labels that each got.

#2 fix: api 연결 설정
  .env
  .env.development
  .env.example
  .env.production
  dev-dist/sw.js
  src/index.css
  src/pages/LandingPage.tsx
  tailwind.config.js
  vite.config.ts
Labels: bug, enhancement

#7 fix: tsconfig.json
  .gitignore
  src/App.js
  src/main.js
  src/pages/LandingPage.js
  src/pages/MapPage.js
  src/types/map.js
  src/utils/spot.js
  src/utils/storage.js
  tsconfig.json
Labels: bug

#8 fix: sw.js 제거
  dev-dist/sw.js
Labels: bug

#45 feat & fix: 프로필에서 포스트 보기 구현 및 친구 상태 문제 해결
  src/App.tsx
  src/components/friend/FriendItem.tsx
  src/components/friend/FriendRequestItem.tsx
  src/components/modal/useActionMenu.tsx
  src/components/profile/ParticipationTab.tsx
  src/components/profile/PostsTab.tsx
  src/components/profile/ProfileBarContent.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileEditForm.tsx
  src/components/profile/ProfileForm.tsx
  src/components/profile/StateTab.tsx
  src/constants/friendRequests.ts
  src/constants/friends.ts
  src/pages/Profile/ProfileEditContainer.tsx
  src/pages/Profile/ProfileEditPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/friend/FriendRequestsPage.tsx
  src/pages/friend/FriendsListPage.tsx
  src/types/friend.ts
  src/types/user.ts
  src/utils/determineProfileType.ts
Labels: bug, enhancement

#48 feat: 이메일 검증 로직 부분 완성
  src/components/auth/signupStep/EmailStep.tsx
  src/components/auth/signupStep/VerifyCodeStep.tsx
  src/pages/auth/SignupPage.tsx
Labels: enhancement

#49 feat: 회원가입 프론트 로직 완성
  components.json
  package-lock.json
  package.json
  src/components/auth/AuthInput.tsx
  src/components/auth/signupStep/AgreeTermStep.tsx
  src/components/auth/signupStep/BirthStep.tsx
  src/components/auth/signupStep/EmailStep.tsx
  src/components/auth/signupStep/GenderStep.tsx
  src/components/auth/signupStep/NameStep.tsx
  src/components/auth/signupStep/NicknameStep.tsx
  src/components/auth/signupStep/PasswordStep.tsx
  src/components/auth/signupStep/VerifyCodeStep.tsx
  src/components/ui/Calendar.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
  src/hooks/useIsMobile.tsx
  src/index.css
  src/lib/utils.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  tailwind.config.js
Labels: enhancement

#59 refactor: api 응답방식 변경 및 템플릿 구조화
  src/api/apiClient.ts
  src/api/authApi.ts
  src/components/auth/signupStep/EmailStep.tsx
  src/components/auth/signupStep/NicknameStep.tsx
  src/components/auth/signupStep/VerifyCodeStep.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: enhancement

#65 fix: friend&profile api 구조 변경
  .vscode/settings.json
  src/api/friendApi.ts
  src/api/profileApi.ts
  src/components/footer/MainFooter.tsx
  src/components/friend/FriendItem.tsx
  src/components/friend/FriendRequestItem.tsx
  src/components/modal/useActionMenu.tsx
  src/components/profile/ProfileBarContent.tsx
  src/components/profile/ProfileContent.tsx
  src/components/search/FriendSearchPanel.tsx
  src/hooks/useFriendSearch.ts
  src/layouts/FriendListLayout.tsx
  src/layouts/ProfileLayout.tsx
  src/pages/Profile/ProfileEditContainer.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/friend/FriendRequestsPage.tsx
  src/pages/friend/FriendsListPage.tsx
  src/pages/friendSearch/FriendSearchPage.tsx
  src/services/friendService.ts
  src/types/user.ts
  src/utils/determineProfileType.ts
  src/utils/determineProfileTypes.ts
Labels: bug

#69 feat: 프로필 성별에 따른 기본 이미지 변경
  public/icons/public/Background.png
  public/icons/public/Man.png
  public/icons/public/User.png
  public/icons/public/Woman.png
  src/components/friend/EmptyState.tsx
  src/components/friend/FriendItem.tsx
  src/components/friend/FriendRequestItem.tsx
  src/components/profile/PostsTab.tsx
  src/components/profile/ProfileBarContent.tsx
  src/components/profile/ProfileContent.tsx
  src/components/search/FriendSearchPanel.tsx
  src/pages/LandingPage.tsx
  src/pages/Profile/ProfileEditPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/friend/FriendRequestsPage.tsx
  src/pages/friend/FriendsListPage.tsx
  src/services/friendService.ts
  src/types/friend.ts
  src/utils/determineProfileTypes.ts
Labels: bug, enhancement

#75 feat: profile 디테일 구조 추가
  public/icons/friend/User.png
  public/icons/profile/cafe.png
  public/icons/profile/drinking.png
  public/icons/profile/exercise.png
  public/icons/profile/game.png
  public/icons/profile/hospital.png
  public/icons/profile/learning.png
  public/icons/profile/meal.png
  public/icons/profile/movie.png
  public/icons/profile/music.png
  public/icons/profile/reading.png
  public/icons/profile/shopping.png
  public/icons/profile/travel.png
  src/api/profileApi.ts
  src/components/friend/EmptyState.tsx
  src/components/friend/FriendItem.tsx
  src/components/friend/FriendRequestItem.tsx
  src/components/modal/useActionMenu.tsx
  src/components/profile/BackgroundImageUploader.tsx
  src/components/profile/ParticipationTab.tsx
  src/components/profile/PostsTab.tsx
  src/components/profile/ProfileAvatar.tsx
  src/components/profile/ProfileBarContent.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileEditContainer.tsx
  src/components/profile/ProfileEditForm.tsx
  src/components/profile/ProfileEditHeader.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/components/profile/StateTab.tsx
  src/components/search/FriendSearchPanel.tsx
  src/hooks/useFriendFilter.ts
  src/hooks/useFriendSearch.ts
  src/layouts/FriendListLayout.tsx
  src/layouts/ProfileLayout.tsx
  src/pages/Profile/ProfileEditContainer.tsx
  src/pages/Profile/ProfileEditPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/friend/FriendRequestsPage.tsx
  src/pages/friend/FriendsListPage.tsx
  src/types/friend.ts
  src/types/user.ts
  src/utils/determineProfileTypes.ts
  src/utils/profileUtils.ts
  src/utils/toFriendSummary.ts
Labels: bug, enhancement

#77 feat: 로그인 구현 완료
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiClient.ts
  src/api/authApi.ts
  src/components/common/FullScreenLoader.tsx
  src/constants/.gitkeep
  src/hooks/useSilentRefresh.ts
  src/pages/LandingRedirect.tsx
  src/pages/auth/LoginPage.tsx
  src/utils/tokenUtils.ts
  tailwind.config.js
  tsconfig.json
Labels: enhancement

#78 fix: 무한로딩 버그 수정
  package-lock.json
  src/api/apiClient.ts
  src/components/common/FullScreenLoader.tsx
  src/pages/LandingPage.tsx
  src/pages/LandingRedirect.tsx
  src/pages/auth/LoginPage.tsx
Labels: bug

#79 feat: 로그인 아이디 값 가져오기
  src/api/authApi.ts
  src/components/footer/MainFooter.tsx
  src/layouts/FriendListLayout.tsx
  src/layouts/ProfileLayout.tsx
Labels: enhancement

#80 refactor: auth 관련 SPA 구조 개선
  src/App.tsx
  src/components/auth/ExistAccount.tsx
  src/components/auth/signupStep/AgreeTermStep.tsx
  src/components/auth/signupStep/EmailStep.tsx
  src/components/auth/signupStep/NicknameStep.tsx
  src/components/auth/signupStep/VerifyCodeStep.tsx
  src/components/header/MainHeader.tsx
  src/layouts/AuthLayout.tsx
  src/pages/LandingPage.tsx
  src/pages/LandingRedirect.tsx
  src/pages/auth/ForgotPasswordPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: enhancement

#92 feat: 검색 기능 및 디테일 수정
  src/components/profile/ParticipationTab.tsx
  src/components/profile/PostsTab.tsx
  src/components/profile/StateTab.tsx
  src/components/search/FriendSearchPanel.tsx
  src/hooks/useSilentRefresh.ts
  src/layouts/FriendListLayout.tsx
  src/layouts/ProfileLayout.tsx
  src/pages/friend/FriendRequestsPage.tsx
  src/pages/friend/FriendsListPage.tsx
  src/pages/friendSearch/FriendSearchPage.tsx
  src/types/search.ts
Labels: enhancement

#93 feat: 앱설치 및 약관 모달 완성
  src/components/auth/AuthFilledButton.tsx
  src/components/auth/signupStep/AgreeTermStep.tsx
  src/components/auth/signupStep/BirthStep.tsx
  src/components/modal/AndroidInstallModal.tsx
  src/components/modal/IosInstallModal.tsx
  src/constants/terms.ts
  src/pages/ErrorPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LandingRedirect.tsx
  tailwind.config.js
Labels: enhancement

#101 feat: footer 로직 구현 완료
  public/icons/common/footerLinkerOff.svg
  public/icons/common/footerLinkerOn.svg
  src/components/footer/FooterItem.tsx
  src/components/footer/MainFooter.tsx
  src/components/modal/useActionMenu.tsx
  src/components/profile/ProfileBarContent.tsx
  src/layouts/AppLayout.tsx
  src/layouts/ProfileLayout.tsx
  src/pages/MapPage.tsx
Labels: enhancement

#124 feat: 프로필 디자인 수정
  public/icons/common/imageUpload.svg
  public/icons/profile/isSelf.svg
  src/App.tsx
  src/components/auth/signupStep/AgreeTermStep.tsx
  src/components/footer/MainFooter.tsx
  src/components/modal/useActionMenu.tsx
  src/components/profile/BackgroundImageUploader.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/layouts/AppLayout.tsx
  src/layouts/FriendListLayout.tsx
  src/layouts/ProfileLayout.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/auth/PasswordResetPage.tsx
  src/pages/post/PostDetailPage.tsx
Labels: enhancement

#126 feat: python AI 추천 로직 연결 성공
  src/api/pythonAPI.ts
  src/components/recommend/recommend.tsx
Labels: enhancement

#135 feat & fix: python AI 추천 구현 및 공통 컴포넌트 생성
  src/api/searchApi.ts
  src/components/linker/LinkerCardItem.tsx
  src/components/map/AddressDisplay.tsx
  src/components/profile/ParticipationTab.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileEditHeader.tsx
  src/components/profile/StateTab.tsx
  src/components/search/TotalSearchPanel.tsx
  src/constants/categoryData.ts
  src/pages/MapPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/friend/FriendsListPage.tsx
  src/types/user.ts
Labels: enhancement

#142 feat: 계좌 관리 페이지 입출금 액수 추가
  src/pages/account/AccountEditPage.tsx
  src/pages/account/AccountPage.tsx
Labels: enhancement

#151 feat: 계좌 관리 페이지 입력 로직 개선
  src/App.tsx
  src/api/apiClient.ts
  src/components/common/ProtectedRoute.tsx
  src/components/footer/TeamNameFooter.tsx
  src/components/modal/DesktopInstallModal.tsx
  src/components/modal/MacInstallModal.tsx
  src/layouts/AuthLayout.tsx
  src/pages/ErrorPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LandingRedirect.tsx
  src/pages/account/AccountPage.tsx
  src/types/error.ts
Labels: enhancement

#155 fix: 검색 및 프로필 디테일 수정
  src/api/searchApi.ts
  src/components/friend/FriendItem.tsx
  src/components/header/SearchHeader.tsx
  src/components/profile/ProfileBarContent.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileEditForm.tsx
  src/components/search/TotalSearchPanel.tsx
  src/hooks/useFriendSearch.ts
  src/pages/Profile/ProfilePage.tsx
  src/pages/friendSearch/TotalSearchPage.tsx
  src/services/friendService.ts
  src/utils/determineProfileTypes.ts
Labels: bug

#163 fix: AI 지도 이동마다 추천 로직 작동
  src/api/pythonAPI.ts
  src/components/map/AddressDisplay.tsx
Labels: enhancement

#164 feat: 비로그인 접속 방지 구현 + 토큰 관리 방식 변경
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiClient.ts
  src/api/authApi.ts
  src/api/plainApiClient.ts
  src/components/footer/FooterItem.tsx
  src/components/footer/MainFooter.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/hooks/useFocusRefresh.ts
  src/hooks/useSilentRefresh.ts
  src/hooks/useStomp.ts
  src/layouts/AccountLayout.tsx
  src/layouts/AppLayout.tsx
  src/layouts/ProtectedLayout.tsx
  src/pages/LandingRedirect.tsx
  src/pages/MapPage.tsx
  src/pages/account/AccountEditPage.tsx
  src/pages/account/AccountPage.tsx
  src/pages/pay/PayRedirectPage.tsx
  src/store/authStore.ts
  src/types/auth.ts
  src/utils/refreshQueue.ts
  src/utils/retryWithBackoff.ts
Labels: bug, enhancement

#180 feat: 푸터 반응형 디자인 개선 및 특정 페이지에서 제거, 스크롤 방지 테스트 구현
  src/components/chat/ChatInput.tsx
  src/components/chat/MessageList.tsx
  src/components/chat/RoomMemberSheet.tsx
  src/components/common/FullScreenLoader.tsx
  src/components/footer/FooterItem.tsx
  src/components/footer/MainFooter.tsx
  src/components/footer/TeamNameFooter.tsx
  src/components/header/BackChatProfileHeader.tsx
  src/components/header/BackTitleHeader.tsx
  src/components/header/ChatHeader.tsx
  src/components/header/MainHeader.tsx
  src/components/header/ProfileHeader.tsx
  src/components/header/SearchHeader.tsx
  src/components/linker/LinkerDetailModal.tsx
  src/components/modal/useActionMenu.tsx
  src/components/search/TotalSearchPanel.tsx
  src/constants/categoryData.ts
  src/hooks/useLockScroll.ts
  src/hooks/usePreventTouchScroll.ts
  src/index.css
  src/layouts/AccountLayout.tsx
  src/layouts/AuthLayout.tsx
  src/layouts/ChatLayout.tsx
  src/pages/MapPage.tsx
  src/pages/account/AccountPage.tsx
Labels: enhancement

#182 fix: style 디테일 수정
  src/components/friend/EmptyState.tsx
  src/components/map/AddressDisplay.tsx
  src/components/post/PostForm.tsx
  src/components/profile/BackgroundImageUploader.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileEditContainer.tsx
  src/components/profile/ProfileEditForm.tsx
  src/components/search/TotalSearchPanel.tsx
  src/pages/friend/FriendRequestsPage.tsx
  src/pages/post/PostDetailPage.tsx
Labels: bug, enhancement

#188 fix: 친구 리스트 조회
  src/api/friendApi.ts
Labels: enhancement

#195 fix: style 디테일 수정
  src/components/chat/RoomMemberSheet.tsx
  src/components/linker/LinkerCardItem.tsx
  src/components/profile/BackgroundImageUploader.tsx
  src/components/profile/ParticipationTab.tsx
  src/components/profile/ProfileContent.tsx
  src/components/profile/ProfileEditContainer.tsx
  src/components/profile/ProfileImageUploader.tsx
Labels: enhancement

#204 style: 포스트, 맵 등 디자인 디테일 개선
  public/icons/common/createChat.svg
  public/icons/mapicon/currentLocation.svg
  public/icons/mapicon/findLocation.svg
  public/icons/mapicon/recommendAi.svg
  src/components/common/ActionCircleButton.tsx
  src/components/linker/LinkerDetailModal.tsx
  src/components/post/PostForm.tsx
  src/index.css
  src/layouts/AppLayout.tsx
  src/layouts/ChatLayout.tsx
  src/pages/MapPage.tsx
  src/pages/account/AccountPage.tsx
  src/pages/chat/RoomCreatePage.tsx
  src/pages/post/PostCreatePage.tsx
  src/pages/post/PostDetailPage.tsx
Labels: enhancement

#205 fix: 검색 timeout 조정
  src/components/search/TotalSearchPanel.tsx
Labels: bug

#226 feat: Map 스크롤 해제
  compose.yaml
  src/components/chat/ChatToasts.tsx
  src/pages/MapPage.tsx
Labels: enhancement

#231 style: 링커 검색 및 추천 디자인 개선
  compose.yaml
  index.html
  src/components/footer/TeamNameFooter.tsx
  src/components/map/AddressDisplay.tsx
  src/components/search/SearchPanel.tsx
  src/components/search/TotalSearchPanel.tsx
  src/pages/MapPage.tsx
Labels: enhancement

#252 feat: 배포 수정 및 프로필 기본 배경 개선
  compose.yaml
  public/icons/profile/Background.png
  src/components/map/AddressDisplay.tsx
Labels: bug, enhancement
